"""Initial migration for the project, containing the Item model

Revision ID: b64b2dcb690f
Revises: 
Create Date: 2020-07-25 20:12:12.323653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b64b2dcb690f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item",
        sa.Column("id_", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.Column("key", sa.String(length=64), nullable=True),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id_"),
        sa.UniqueConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item")
    # ### end Alembic commands ###
